apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav
  namespace: senaev-com
  labels:
    app: webdav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webdav
  template:
    metadata:
      labels:
        app: webdav
    spec:
      containers:
        - name: webdav
          image: bytemark/webdav
          env:
            - name: AUTH_TYPE
              value: Digest
            - name: USERNAME
              value: admin
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: WEBDAV_PASSWORD
          ports:
            - containerPort: 80
          volumeMounts:
            - name: data
              mountPath: /var/lib/dav
      volumes:
        - name: data
          hostPath:
            path: /home/ubuntu/webdav
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: webdav
  namespace: senaev-com
spec:
  selector:
    app: webdav
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
