apiVersion: v2
name: vault
description: HashiCorp Vault (server only, no injector)
type: application
version: 0.1.0
appVersion: "1"
kubeVersion: ">=1.21.0"
dependencies:
  - name: vault
    version: "0.32.0"
    repository: "file://./charts/vault-0.32.0.tgz"
